twitter: ""
github: ""
linkedin: "https://de.linkedin.com/company/deepwave-e-v"
youtube: "https://www.youtube.com/channel/UCOuPrqLgaFa5ATC-kVpJ5ZA"
dribbble: ""
instagram: "https://www.instagram.com/deepwave_ocean_org/"
facebook: ""
medium: ""
patreon: "https://www.patreon.com/DEEPWAVEeV"
paypal: ""
unsplash: ""
