baseURL: "https://meeresoffensive.deepwave.org"
languageCode: "de-DE"
title: "DEEPWAVE e.V."
markup:
  goldmark:
    renderer:
      unsafe: true  # default is false // https://stackoverflow.com/questions/63198652/hugo-shortcode-ignored-saying-raw-html-omitted
pygmentsstyle: 'monokai'
metaDataFormat: yaml
params:
  cloudinary_url: https://res.cloudinary.com/deepwave-org/image/upload

# Theme settings
theme: hugo-theme-novela
paginate: 8
social:
  twitter: "#"
  github: "#"
  instagram: "https://www.instagram.com/deepwave_ocean_org/"
  linkedin: "https://de.linkedin.com/company/deepwave-e-v"
  dribbble: "#"
  youtube: "https://www.youtube.com/channel/UCOuPrqLgaFa5ATC-kVpJ5ZA"
taxonomies:
  category: categories
  author: authors
