baseURL: "https://example.com"
languageCode: "de-DE"
title: "DEEPWAVE e.V."
pygmentsstyle: 'monokai'
metaDataFormat: yaml
params:
  cloudinary_url: https://res.cloudinary.com/deepwave-org/image/upload

# Theme settings
theme: hugo-theme-novela
paginate: 8
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  category: categories
  author: authors
